// import localFont from "next/font/local";
// import "./globals.css";
// import Header from "@/components/ui/Header";
// import PageTransition from "@/components/ui/PageTransition";
// import StairTransition from "@/components/ui/StairTransition";
// import Image from "next/image";
// import code from '../public/assets/pic/code.jpg'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app..",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
      
//         className={`${geistSans.variable} ${geistMono.variable} antialiased ` }
//       >
//         {/* <Image src={code}  alt="code"/> */}
//         <div className=" ">
//         <Header/>
//         <StairTransition/>
//         <PageTransition>

//         {children}
//         </PageTransition>
//           </div>
//       </body>
//     </html>
//   );
// }


import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/ui/Header";
import PageTransition from "@/components/ui/PageTransition";
import StairTransition from "@/components/ui/StairTransition";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('../public/assets/pic/code-text.jpg')] bg-cover bg-no-repeat relative min-h-screen`}
      >
        {/* Black shadow overlay */}
        <div className="absolute inset-0 bg-black opacity-45 min-h-screen"></div>

        {/* Main content */}
        <div className="relative z-50">
          <Header />
          <StairTransition />
          <PageTransition>
            {children}
          </PageTransition>
        </div>
      </body>
    </html>
  );
}

